# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS Framworks' do
  # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!
  #pod 'FBSDKLoginKit'
  #pod 'FacebookCore'
  #pod 'FacebookLogin'
  pod 'Firebase/Auth'

  # Pods for iOS Framworks

  target 'iOS FramworksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS FramworksUITests' do
    # Pods for testing
  end

end
