platform :ios, '9.0'

target 'cocoapods' do
  use_frameworks!

  pod 'Alamofire'

  target 'cocoapodsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cocoapodsUITests' do
    # Pods for testing
  end

end
